// <auto-generated />
using IndicVest.Infrastructure.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IndicVest.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(IndicVestContext))]
    [Migration("20260905165032_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IndicVest.Core.Domain.Entities.Financial.Country", b =>
                {
                    b.Property<int>("IdCountry")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCountry"));

                    b.Property<string>("ISOCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("IdCountry");

                    b.HasIndex("ISOCode")
                        .IsUnique();

                    b.ToTable("Countries", (string)null);
                });

            modelBuilder.Entity("IndicVest.Core.Domain.Entities.Financial.Indicator", b =>
                {
                    b.Property<int>("IdIndicator")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdIndicator"));

                    b.Property<int>("IdCountry")
                        .HasColumnType("integer");

                    b.Property<int>("IdMacroIndicator")
                        .HasColumnType("integer");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("IdIndicator");

                    b.HasIndex("IdMacroIndicator");

                    b.HasIndex("IdCountry", "IdMacroIndicator", "Year")
                        .IsUnique();

                    b.ToTable("Indicators", (string)null);
                });

            modelBuilder.Entity("IndicVest.Core.Domain.Entities.Financial.MacroIndicator", b =>
                {
                    b.Property<int>("IdMacroIndicator")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMacroIndicator"));

                    b.Property<bool>("IsHighBetter")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(5,4)");

                    b.HasKey("IdMacroIndicator");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("MacroIndicators", (string)null);
                });

            modelBuilder.Entity("IndicVest.Core.Domain.Entities.Financial.ReturnRate", b =>
                {
                    b.Property<int>("IdReturnRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdReturnRate"));

                    b.Property<decimal>("MaxReturnRate")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("MinReturnRate")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("IdReturnRate");

                    b.ToTable("ReturnRates", null, t =>
                        {
                            t.HasCheckConstraint("CK_ReturnRate_MinLessThanMax", "\"MinReturnRate\" < \"MaxReturnRate\"");
                        });

                    b.HasData(
                        new
                        {
                            IdReturnRate = 1,
                            MaxReturnRate = 0.15m,
                            MinReturnRate = 0.02m
                        });
                });

            modelBuilder.Entity("IndicVest.Core.Domain.Entities.Financial.Indicator", b =>
                {
                    b.HasOne("IndicVest.Core.Domain.Entities.Financial.Country", "Country")
                        .WithMany("Indicators")
                        .HasForeignKey("IdCountry")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IndicVest.Core.Domain.Entities.Financial.MacroIndicator", "MacroIndicator")
                        .WithMany("Indicators")
                        .HasForeignKey("IdMacroIndicator")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("MacroIndicator");
                });

            modelBuilder.Entity("IndicVest.Core.Domain.Entities.Financial.Country", b =>
                {
                    b.Navigation("Indicators");
                });

            modelBuilder.Entity("IndicVest.Core.Domain.Entities.Financial.MacroIndicator", b =>
                {
                    b.Navigation("Indicators");
                });
#pragma warning restore 612, 618
        }
    }
}
